### PR TITLE
assert: truncate very long objects in test failure messages

### LINKED ISSUE #1525: assert/require.Len doesn't print anything if the slice is too long
Hey there, I encountered this when attempting to use `require.Len` as shown below.

```go
package tester_test

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestVeryLongSlice(t *testing.T) {
	var bigSlice []string
	for i := 0; i < 20000; i++ {
		bigSlice = append(bigSlice, "hello")
	}

	require.Len(t, bigSlice, 10)
}
```

Output of test:

```
=== RUN   TestVeryLongSlice
    tester_test.go:15:
                Error Trace:    C:/Users/Fots/source/tester/tester/tester_test.go:15
                Error:
                Test:           TestVeryLongSlice
--- FAIL: TestVeryLongSlice (0.00s)
FAIL
FAIL    github.com/fgimian/tester/tester        0.150s
FAIL
```

I haven't quite figured out why this happens, although I can imagine the output would be impractically long anyway. Worst of all, the main assertion message is not displayed which is quite confusing (especially to someone new using the library, like me 😄).

Personally, I think that it would be best not to display the slice at all for the `Len` function, and instead just display:

```
Should have X item(s), but has Y
```

However, I suspect my view on that may not be what some people want. The reason I think it is unwise to print the slice in any form, is that typically when many people are testing for the length of a slice, they may be comparing to a relatively large slice of items (e.g. the output of a mocked API call or similar).

An additional point that I believe has been discussed before is the inconsistency with argument ordering for the `Len` function which takes the `actual` first and `expected` second.

Cheers
Fotis

### PR DESCRIPTION
**Pull request by brackendawson**
## Summary
Truncate object representations in test failure output messages that would cause the message to be too long to scan.

This is a different approach than that in #1559. I feel this is more appropriate because is it safer. The other approach has the potential to allocate excessive memory and to print excessive output to the console.

## Changes
* Make the message line indenter show an appropriate error if it fails to scan a line from the message.
* Use the existing `truncatingFormat` function to truncate potentially long objects in assertions which format expected/actual values in full.
* Parameterize the format string used by `truncatingFormat`.
* Reduce the limit used by `truncatingFormat` by almost half to support failure messages showing both long expected and long actual values on the same line.
* Change the format of `NotSubset` from `%q` to `%#v` to match that of `Subset`.

## Motivation
So that people don't see no output in the failure message when making assertions (such as `Len`) against very long objects.

## Related issues
Closes #1525

### CODE REVIEW

File: assert/assertions.go [hunk 1]
```diff
@@ -604,23 +605,24 @@ func samePointers(first, second interface{}) (same bool, ok bool) {
...
 //
 // This helps keep formatted error messages lines from exceeding the
 // bufio.MaxScanTokenSize max line length that the go testing framework imposes.
-func truncatingFormat(data interface{}) string {
-	value := fmt.Sprintf("%#v", data)
-	max := bufio.MaxScanTokenSize - 100 // Give us some space the type info too if needed.
+func truncatingFormat(format string, data interface{}) string {
+	value := fmt.Sprintf(format, data)
+	// Give us space for two truncated objects and the surrounding sentence.
+	max := bufio.MaxScanTokenSize/2 - 100
```
Comment (ccoVeille) [inline assert/assertions.go]: Do not shadow built-in `max` function

File: assert/assertions.go [hunk 2]
```diff
@@ -793,7 +795,7 @@ func Empty(t TestingT, object interface{}, msgAndArgs ...interface{}) bool {
 		if h, ok := t.(tHelper); ok {
 			h.Helper()
 		}
-		Fail(t, fmt.Sprintf("Should be empty, but was %v", object), msgAndArgs...)
+		Fail(t, fmt.Sprintf("Should be empty, but was %s", truncatingFormat("%v", object)), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:798]: Others are like this

```suggestion
		Fail(t, fmt.Sprintf("Should be empty, but was %s", truncatingFormat("%#v", object)), msgAndArgs...)
```

File: assert/assertions.go [hunk 3]
```diff
@@ -836,11 +838,11 @@ func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{})
 	}
 	l, ok := getLen(object)
 	if !ok {
-		return Fail(t, fmt.Sprintf("\"%v\" could not be applied builtin len()", object), msgAndArgs...)
+		return Fail(t, fmt.Sprintf("%q could not be applied builtin len()", truncatingFormat("%v", object)), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:841]:
```suggestion
		return Fail(t, fmt.Sprintf("%q could not be applied builtin len()", truncatingFormat("%#v", object)), msgAndArgs...)
```

File: assert/assertions.go [hunk 4]
```diff
@@ -836,11 +838,11 @@ func Len(t TestingT, object interface{}, length int, msgAndArgs ...interface{})
...
 	}
 
 	if l != length {
-		return Fail(t, fmt.Sprintf("\"%v\" should have %d item(s), but has %d", object, length, l), msgAndArgs...)
+		return Fail(t, fmt.Sprintf("%q should have %d item(s), but has %d", truncatingFormat("%v", object), length, l), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:845]:
```suggestion
		return Fail(t, fmt.Sprintf("%q should have %d item(s), but has %d", truncatingFormat("%#v", object), length, l), msgAndArgs...)
```

File: assert/assertions.go [hunk 5]
```diff
@@ -1056,7 +1058,7 @@ func Subset(t TestingT, list, subset interface{}, msgAndArgs ...interface{}) (ok
 			return Fail(t, fmt.Sprintf("%#v could not be applied builtin len()", list), msgAndArgs...)
 		}
 		if !found {
-			return Fail(t, fmt.Sprintf("%#v does not contain %#v", list, element), msgAndArgs...)
+			return Fail(t, fmt.Sprintf("%s does not contain %#v", truncatingFormat("%#v", list), element), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:1061]:
```suggestion
			return Fail(t, fmt.Sprintf("%s does not contain %s", truncatingFormat("%#v", list), element), msgAndArgs...)
```

File: assert/assertions.go [hunk 6]
```diff
@@ -1700,7 +1702,7 @@ func ErrorContains(t TestingT, theError error, contains string, msgAndArgs ...in
 
 	actual := theError.Error()
 	if !strings.Contains(actual, contains) {
-		return Fail(t, fmt.Sprintf("Error %#v does not contain %#v", actual, contains), msgAndArgs...)
+		return Fail(t, fmt.Sprintf("Error %s does not contain %#v", truncatingFormat("%#v", actual), contains), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:1705]:
```suggestion
		return Fail(t, fmt.Sprintf("Error %s does not contain %s", truncatingFormat("%#v", actual), contains), msgAndArgs...)
```

File: assert/assertions.go [hunk 7]
```diff
@@ -1031,10 +1033,10 @@ func Subset(t TestingT, list, subset interface{}, msgAndArgs ...interface{}) (ok
 			av := actualMap.MapIndex(k)
 
 			if !av.IsValid() {
-				return Fail(t, fmt.Sprintf("%#v does not contain %#v", list, subset), msgAndArgs...)
+				return Fail(t, fmt.Sprintf("%s does not contain %s", truncatingFormat("%#v", list), truncatingFormat("%#v", subset)), msgAndArgs...)
 			}
 			if !ObjectsAreEqual(ev.Interface(), av.Interface()) {
-				return Fail(t, fmt.Sprintf("%#v does not contain %#v", list, subset), msgAndArgs...)
+				return Fail(t, fmt.Sprintf("%s does not contain %s", truncatingFormat("%#v", list), truncatingFormat("%#v", subset)), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go:1039]: I'm a bit worried about these 2

We have 2 list that could be huge that would be truncated here, but displayed on the same line.

Maybe it works because of the max/2-200, but I feel like the line might difficult to read because of the lack of \n that we have for almost all others failures

File: assert/assertions.go [hunk 8]
```diff
@@ -1106,7 +1108,7 @@ func NotSubset(t TestingT, list, subset interface{}, msgAndArgs ...interface{})
 			}
 		}
 
-		return Fail(t, fmt.Sprintf("%q is a subset of %q", subset, list), msgAndArgs...)
+		return Fail(t, fmt.Sprintf("%s is a subset of %s", truncatingFormat("%#v", subset), truncatingFormat("%#v", list)), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go]: See https://github.com/stretchr/testify/pull/1646#discussion_r2353499286

File: assert/assertions.go [hunk 9]
```diff
@@ -1128,7 +1130,7 @@ func NotSubset(t TestingT, list, subset interface{}, msgAndArgs ...interface{})
 		}
 	}
 
-	return Fail(t, fmt.Sprintf("%q is a subset of %q", subset, list), msgAndArgs...)
+	return Fail(t, fmt.Sprintf("%s is a subset of %s", truncatingFormat("%#v", subset), truncatingFormat("%#v", list)), msgAndArgs...)
```
Comment (ccoVeille) [inline assert/assertions.go]: See https://github.com/stretchr/testify/pull/1646#discussion_r2353499286

File: assert/assertions_test.go [hunk 10]
```diff
@@ -3969,3 +3969,244 @@ func TestNotErrorAs(t *testing.T) {
...
+func TestContainsWithSliceTooLongToPrint(t *testing.T) {
+	t.Parallel()
+	mockT := new(mockTestingT)
+	longSlice := make([]int, 1_000_000)
+	Contains(mockT, longSlice, 1)
+	Contains(t, mockT.errorString(), `
+	Error Trace:	
+	Error:      	[]int{0, 0, 0,`)
+	Contains(t, mockT.errorString(), `<... truncated> does not contain 1`)
+}
```
Comment (ccoVeille) [inline assert/assertions_test.go:3993]: Can't we define the max value via a global variable used only in tests. Defined to something like 10, and then we check the exact rendering, and not something that check for piece of text

File: assert/assertions.go (hunk 2 above)
Comment (brackendawson) [reply assert/assertions.go:798]: This instance of truncatingFormat must use `%v` because the un-truncated format it replaces does, otherwise it would change the format of the message. This PR only truncates messages that are so long that they cause Go to output no message at all.

File: assert/assertions.go (hunk 3 above)
Comment (brackendawson) [reply assert/assertions.go:841]: This one was `\"%v\"`, which is equivalent to  `\"%s\"` with truncatingFormat(%v), which is equivelant to `%q` with truncatingFormat(%v)

File: assert/assertions.go (hunk 4 above)
Comment (brackendawson) [reply assert/assertions.go:845]: This one was `\"%v\"`, which is equivalent to  `\"%s\"` with truncatingFormat(%v), which is equivelant to `%q` with truncatingFormat(%v)

File: assert/assertions.go (hunk 5 above)
Comment (brackendawson) [reply assert/assertions.go:1061]: The second formatted variable (uses `element`) must not change.

File: assert/assertions.go (hunk 7 above)
Comment (brackendawson) [reply assert/assertions.go:1039]: I agree about the hard to read part, but that would be a different issue. Again the only aim here is to show strings which previously got swallowed.

File: assert/assertions.go (hunk 8 above)
Comment (brackendawson) [reply assert/assertions.go]: I am actually wrong here, it should be:
```suggestion
		return Fail(t, fmt.Sprintf("%s is a subset of %s", truncatingFormat("%q", subset), truncatingFormat("%q", list)), msgAndArgs...)
```
%q quotes the elements of a list o.0

I've raised #1800 to fix the formatting later.

File: assert/assertions_test.go (hunk 10 above)
Comment (brackendawson) [reply assert/assertions_test.go:3993]: We can't because that wouldn't prove that the truncated messages make it through the scanner.

Comment (brackendawson) [reply assert/assertions_test.go:3993]: We can't because that wouldn't prove that the truncated message makes it through the reader.

**Comment by brackendawson** [comment]
Thank you @ccoVeille. I've updated the PR to address some comments and responded with a defence in the others.

File: assert/assertions.go (hunk 6 above)
Comment (brackendawson) [reply assert/assertions.go:1705]: The second formatted variable (uses `contains`) must not change.

File: assert/assertions.go (hunk 7 above)
Comment (ccoVeille) [reply assert/assertions.go:1039]: I understand your point. But mine wasn't about readability.

I just wanted to make sure that comparing two slices that very long won't lead to a line that cannot be displayed.

I feel like that tge point of the max/2-200 but I wanted to make sure it would work.

**Review by ccoVeille — APPROVED** [review]

File: assert/assertions.go (hunk 7 above)
Comment (brackendawson) [reply assert/assertions.go:1039]: Yes, that doesn't sit 100% with me either. When we follow this up with #1235 and reduce the max length much further I will be very confident.
