### PR TITLE
Time duration diff format

### LINKED ISSUE #626: formatUnequalValues with %v instead of %#v?
Is there a way to get the default format when assert.Equal fails? Specifically, I am comparing time.Duration values, and getting an int64 of microseconds is not as friendly as Duration.String. ([example](https://play.golang.org/p/vA3xeX5-OEr))

I understand that the current behavior is generally more useful. Rather than changing the default, I am hoping there is some option I can invoke to make my own test output more readable.

Sample output:
```
        assertions.go:256:
                        Error Trace:    integration_test.go:125
                        Error:          Not equal:
                                        expected: 180000000000
                                        actual  : 0
                        Test:           TestDurationFormat
```

Preferred output:
```
        assertions.go:256:
                        Error Trace:    integration_test.go:125
                        Error:          Not equal:
                                        expected: 3m0s
                                        actual  : 0s
                        Test:           TestDurationFormat
```

### PR DESCRIPTION
**Pull request by devdinu**
Time Duration mismatch from nanoseconds (int64) to readable format.

Fixes #626.

### CODE REVIEW

**Comment by devdinu** [comment]
@boyan-soubachov could you review this and merge

File: assert/assertions.go [hunk 1]
```diff
@@ -357,9 +357,11 @@ func formatUnequalValues(expected, actual interface{}) (e string, a string) {
 		return fmt.Sprintf("%T(%#v)", expected, expected),
 			fmt.Sprintf("%T(%#v)", actual, actual)
 	}
-
-	return fmt.Sprintf("%#v", expected),
-		fmt.Sprintf("%#v", actual)
+	switch expected.(type) {
```
Comment (boyan-soubachov) [inline assert/assertions.go]: Any reason for preferring a `switch` over a plain `if`? Would it make sense to have it as an:
```
if expected.(type) == time.Duration {
    return ...
}
return ...
```
and if we need to add more cases in the future, we can convert to a `switch`?

File: assert/assertions_test.go [hunk 2]
```diff
@@ -1499,6 +1499,15 @@ Diff:
 	Equal(t, expected, actual)
 }
 
+func TestTimeEquality(t *testing.T) {
```
Comment (boyan-soubachov) [inline assert/assertions_test.go]: Would it make sense to have a more explicit test name which very apparently describes what we're testing? A suggestion would be: `TestTimeEqualityFormatting`.

Comment (devdinu) [reply assert/assertions_test.go]: Updated.

File: assert/assertions.go (hunk 1 above)
Comment (devdinu) [reply assert/assertions.go]: type check needs switch
