### PR TITLE
Document consequences of calling t.FailNow()

### LINKED ISSUE #1701: Calling MethodCalled() in a goroutine can result in a call to t.FailNow()
## Description
I'm using this library indirectly, through `vektra/mockery`. I have a mock that I use in a goroutine, and I don't expect any calls on it. However, because of a bug in my code, there sometimes is an unexpected calls. This results in a call to `t.FailNow()`, which causes necessary cleanup to be skipped and the entire test suite to hang.

Looking at `MethodCalled()`, we can see several calls to `m.fail()`:

https://github.com/stretchr/testify/blob/7c367bb7bc7dad2d8b17921a604157dc27ebe06f/mock/mock.go#L509-L524

and `fail()` calls `T.FailNow()`: https://github.com/stretchr/testify/blob/7c367bb7bc7dad2d8b17921a604157dc27ebe06f/mock/mock.go#L352

Looking at [the documentation of `FailNow()`](https://pkg.go.dev/testing#T.FailNow), we can read the following: 

> `FailNow` must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test.

I think both `m.fail()` and `m.MethodCalled()` should come with the same warning.

## Step To Reproduce

create a goroutine that calls a mock, and performs an unexpected call on the mock, then closes a channel that should cause the main thread to hang until it is closed

## Expected behavior

The channel should still get closed.

## Actual behavior

The test hangs forever.

### PR DESCRIPTION
**Pull request by greg0ire**
## Summary

These comments are adapted from `t.FailNow()`'s own documentation.

## Changes

I added warnings on high-level APIs likely to be used by end users, and leading to `t.FailNow()` being called.

## Motivation

Such additional documentation can spare users headache in situations where ignoring the warnings would lead to test suites hanging forever

## Related issues

Closes #1701

### CODE REVIEW

File: mock/mock.go [hunk 1]
```diff
@@ -332,6 +332,8 @@ func (m *Mock) TestData() objx.Map {
 */
 
 // Test sets the test struct variable of the mock object
+// Test should not be called on an object that is going to be used in a
```
Comment (brackendawson) [inline mock/mock.go:335]: Need to add a `.` on the previous sentence:
image

**Review by brackendawson — CHANGES_REQUESTED** [review]

File: mock/mock.go (hunk 1 above)
Comment (brackendawson) [reply mock/mock.go:335]: While here, we might improve the existing doc?
``go
// Test sets the [TestingT] on which errors will be reported, otherwise errors will cause a panic.

**Review by brackendawson — APPROVED** [review]
LGTM
