### PR TITLE
assert: fix TestEventuallyTimeout

### LINKED ISSUE #1411: TestEventuallyIssue805: flaky test
We still have flaky tests. It looks like #865 did not fix everything related to #805 and #835.
```console
$ go test -race -failfast -count 100 -run TestEventuallyIssue805 ./assert 
--- FAIL: TestEventuallyIssue805 (0.00s)
    assertions_test.go:2815: 
        	Error Trace:	
        	Error:      	Should be false
        	Test:       	TestEventuallyIssue805
FAIL
FAIL	github.com/stretchr/testify/assert	0.451s
FAIL
```

Cc: @snebel29

### PR DESCRIPTION
**Pull request by dolmen**
## Summary
Fix TestEventuallyIssue805 which was flaky because of the use of a timer that has exactly the same duration as the Eventually timout. But time is not a synchronization primitive.

## Changes
* Now we use channels to ensure that the condition is still running and Eventually times out before checking its return value.
* The test is also renamed to TestEventuallyTimeout to more clearly show its purpose.

## Motivation
Test was flaky (see #1411). CI was unreliable.

## Related issues
Closes #1411.
Related to #805, #869, #865.

### CODE REVIEW

**Review by SuperQ — APPROVED** [review]
Nice find

**Comment by SuperQ** [comment]
I'd also recommend changing the timer values for this to be similar to the other timer tests to be values larger than a single millisecond/microsecond. I've seen cases where CI tests be flaky because of too-close (+-1ms) a timer wait.

**Comment by brackendawson** [comment]
The durations shouldn't need to be increased now because there are no longer two short timers running at the same time. Increasing them would only slow down the test. I'd approve this as is.

I've found similar cases where a potential allocation by `time.After` can slow down the creation of one timer after the other has started, this can be solved like so: https://github.com/stretchr/testify/pull/1124/commits/8cd90172afd36768960e21660b1ef09c4bfd6d46

File: assert/assertions_test.go [hunk 1]
```diff
@@ -2807,12 +2807,31 @@ func TestNeverTrue(t *testing.T) {
...
-func TestEventuallyIssue805(t *testing.T) {
+// Check that a long running condition doesn't block Eventually.
+// See issue 805 (and its long tail of following issues)
+func TestEventuallyTimeout(t *testing.T) {
 	mockT := new(testing.T)
 
 	NotPanics(t, func() {
-		condition := func() bool { <-time.After(time.Millisecond); return true }
+		t.Log("start")
+		done, done2 := make(chan bool), make(chan bool)
```
Comment (stevenh) [inline assert/assertions_test.go:2817]: It's idiomatic to use a `struct{}` instead of `bool` as it takes no space.
```suggestion
		done, done2 := make(chan struct{}), make(chan struct{})
```

**Review by stevenh — CHANGES_REQUESTED** [review]
Nice approach to eliminate the timing totally.

I would use the idiomatic `chan struct{}` for the done channel's, but that's just a nit given it's a test.

Not sure if you intended to leave the logging in or not?

File: assert/assertions_test.go [hunk 2]
```diff
@@ -2807,12 +2807,31 @@ func TestNeverTrue(t *testing.T) {
...
 
-func TestEventuallyIssue805(t *testing.T) {
+// Check that a long running condition doesn't block Eventually.
+// See issue 805 (and its long tail of following issues)
+func TestEventuallyTimeout(t *testing.T) {
 	mockT := new(testing.T)
 
 	NotPanics(t, func() {
-		condition := func() bool { <-time.After(time.Millisecond); return true }
+		t.Log("start")
```
Comment (brackendawson) [inline assert/assertions_test.go:2816]: Good spot on the t.Log @stevenh. Looking at the rest of the package there is no other test which logs on success, so we should probably hold that convention.

**Review by brackendawson — CHANGES_REQUESTED** [review]

File: assert/assertions_test.go (hunk 1 above)
Comment (dolmen) [reply assert/assertions_test.go]: Thanks for the catch.

Fixed (amending my commit).

File: assert/assertions_test.go (hunk 2 above)
Comment (dolmen) [reply assert/assertions_test.go:2816]: Well, I think that the logs are helpful to show what happens. In fact the lack of logging was what made debugging the issue harder.

The sequence of events is really important in this test, and the log output allows to validate visually that everything happens in the right order. I think this will be useful for regression testing if the test has to be changed later.

This is the only test that has verbose log output, but I think that's is what verbose output is for. This is a case that is worth it.

The log messages could be improved though. Suggestions welcome.

Comment (stevenh) [reply assert/assertions_test.go:2816]: In my opinion good comments would be more valuable, you already have some.

The goal as you say is to help those who might have to debug it in the future, by making it clear why flow is how it is.

I don't think you need logging to achieve this, and the current output e.g. `ok1` and `ok2` doesn't add any value as it doesn't describe what is happening or why, leaving the user thinking what is `ok1` etc?

Comment (dolmen) [reply assert/assertions_test.go]: Logs removed.

**Review by craig65535 — APPROVED** [review]

**Comment by dolmen** [comment]
Following [my announcement on Slack](https://gophers.slack.com/archives/C92321HDJ/p1698873887431609), I'm pinging all other co-maintainers.

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
I will be happy to merge this once @brackendawson has reviewed again after the request for changes.

**Review by stevenh — APPROVED** [review]

**Review by brackendawson — APPROVED** [review]
Looks great!
