### PR TITLE
Fix #136 - Empty returns true for nil pointers

### LINKED ISSUE #136: Empty doesn't check if a pointer value is nil
--- FAIL: TestMain (0.00s)
            Location:       testingutil.go:43
            Error:          Should be empty, but was <nil>

What's wrong with this picture? ;)

### PR DESCRIPTION
**Pull request by ernesto-jimenez**

### CODE REVIEW

**Comment by ernesto-jimenez** [comment]
@DAddYE mind double checking?

It's a fix for #136

File: assert/assertions.go [hunk 1]
```diff
@@ -358,6 +358,9 @@ func isEmpty(object interface{}) bool {
 		}
 	case reflect.Ptr:
 		{
+			if objValue.IsNil() {
+				return true
+			}
 			switch object.(type) {
 			case *time.Time:
```
Comment (ernesto-jimenez) [inline assert/assertions.go]: We probably should not have a special case for `time.Time`.

Comment (ernesto-jimenez) [inline assert/assertions.go]: Probably related: https://github.com/stretchr/testify/issues/123
