### PR TITLE
assert: Fix EqualValues to handle overflow/underflow

### LINKED ISSUE #1462: assert: EqualValues does not check for overflows
When asserting two numeric values with EqualValues, it passes if one is the overflowed value of the other.

example: https://go.dev/play/p/KZsFh7FnBVc

```go
func TestEqualValues(t *testing.T) {
	var a int8 = 14
	var b int = 270
	assert.Equal(t, b, a)       // fails because of type mismatch
	assert.EqualValues(t, b, a) // passes
}
```

### PR DESCRIPTION
**Pull request by arjunmahishi**
## Summary

The underlying function `ObjectsAreEqualValues` did not handle overflow/underflow of values while converting one type to another for comparison. For example:

```go
    EqualValues(t, int(270), int8(14))
```

would return `true`, even though the values are not equal. Because, when you convert `int(270)` to `int8`, it overflows and becomes 14 `(270 % 256 = 14)`

## Changes

This commit fixes that by making sure that the conversion always happens from the **smaller type to the larger type**, and then comparing the values. Additionally, this commit also separates out the test cases of `ObjectsAreEqualValues` from `TestObjectsAreEqual`.

## Related issues

Closes #1462

### CODE REVIEW

File: assert/assertions.go [hunk 1]
```diff
@@ -165,19 +165,40 @@ func ObjectsAreEqualValues(expected, actual interface{}) bool {
...
+			}
+
+			return expectedValue.Convert(actualType).Interface() == actual
+		}
+
 		// Attempt comparison after type conversion
 		return reflect.DeepEqual(expectedValue.Convert(actualType).Interface(), actual)
 	}
 
 	return false
```
Comment (MovieStoreGuy) [inline assert/assertions.go:192]: If it is possible, I would prefer to invert the statements to reduce the indenting?

It makes it easier for me to read (but it doesn't look like it is a practice within the project)

File: assert/assertions_test.go [hunk 2]
```diff
@@ -135,24 +135,34 @@ func TestObjectsAreEqual(t *testing.T) {
...
-	}
+func TestObjectsAreEqualValues(t *testing.T) {
+	now := time.Now()
 
-	tm := time.Now()
-	tz := tm.In(time.Local)
-	if !ObjectsAreEqualValues(tm, tz) {
-		t.Error("ObjectsAreEqualValues should return true for time.Time objects with different time zones")
+	cases := []struct {
+		expected interface{}
```
Comment (MovieStoreGuy) [inline assert/assertions_test.go:144]: I would ask to replace `interface` with `any`

**Review by MovieStoreGuy — COMMENTED** [review]
Minor revision from me, and excuse as I become more familiar with helping to maintain the project.

File: assert/assertions_test.go (hunk 2 above)
Comment (arjunmahishi) [reply assert/assertions_test.go:144]: Sure. I haven't really used generics that much. I keep forgetting that it exists :P

File: assert/assertions.go (hunk 1 above)
Comment (arjunmahishi) [reply assert/assertions.go:192]: Makes sense. will do that and push the changes in a bit.

File: assert/assertions_test.go (hunk 2 above)
Comment (arjunmahishi) [reply assert/assertions_test.go:144]: We can't use generics yet. This project is still on go `v1.17`

https://github.com/stretchr/testify/blob/c3b0c9b4f50cd8320ccdcdfd3ffd6afc5b109c4a/go.mod#L5

File: assert/assertions.go (hunk 1 above)
Comment (arjunmahishi) [reply assert/assertions.go]: Done

**Review by MovieStoreGuy — DISMISSED** [review]

**Review by brackendawson — CHANGES_REQUESTED** [review]
Apparently complex isn't numeric, so this still behaves incorrectly:

```go
	EqualValues(t, complex128(1e+100+1e+100i), complex64(complex(math.Inf(0), math.Inf(0))))
```

I'm open to not fixing this case. Also I wonder why complex isn't numeric.

File: assert/assertions.go [hunk 3]
```diff
@@ -165,17 +165,40 @@ func ObjectsAreEqualValues(expected, actual interface{}) bool {
...
+	}
+
+	return expectedValue.Convert(actualType).Interface() == actual
+}
+
+// isNumericType returns true if the type is one of:
+// int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64,
+// float32, float64
+func isNumericType(t reflect.Type) bool {
+	return t.Kind() >= reflect.Int && t.Kind() <= reflect.Float64
```
Comment (brackendawson) [inline assert/assertions.go:201]: Aha
```suggestion
	return t.Kind() >= reflect.Int && t.Kind() <= reflect.Complex128
```

Comment (arjunmahishi) [reply assert/assertions.go:201]: I don't think `complex` numbers should be included in this bucket. Because We will not be able to convert an `int*` `float*` to `complex*`. So, there is no basis for comparison. 

Also, this condition will make sure that _`int*/float* <> complex*`_ comparisons will always yield `false`
https://github.com/stretchr/testify/blob/2d27e0f92acbd4ef9063399060e58ba3a6867310/assert/assertions.go#L176-L178

---

I tinkered around in the playground to verify this: https://go.dev/play/p/bhIO--yWxMN

Comment (brackendawson) [reply assert/assertions.go:201]: But you can convert a complex128 to a complex64. Your test on L176 already fixes your concern by implicitly dividing the bucket into two. These testcases all pass with my proposed change:
```go
		{complex128(1e+100 + 1e+100i), complex64(complex(math.Inf(0), math.Inf(0))), false},
		{complex64(complex(math.Inf(0), math.Inf(0))), complex128(1e+100 + 1e+100i), false},
		{complex128(1e+100 + 1e+100i), 270, false},
		{270, complex128(1e+100 + 1e+100i), false},
		{complex128(1e+100 + 1e+100i), 3.14, false},
		{3.14, complex128(1e+100 + 1e+100i), false},
		{complex128(1e+10 + 1e+10i), complex64(1e+10 + 1e+10i), true},
		{complex64(1e+10 + 1e+10i), complex128(1e+10 + 1e+10i), true},
```

The interesting part is that 10+0i is mathematically equal to 10. But Go's equality operator [will not perform this operation](https://go.dev/play/p/AMYnvdCfYe1) and the types are truly [not convertible](https://go.dev/play/p/6iqAi5A7r-h) without using the helper functions. So I think it's safe and acceptable to include the behaviour in the above testcases.

Can you show me a testcase which behaves incorrectly?

NB: Careful with untyped literals when experimenting here, they [look like they are convertible](https://go.dev/play/p/5-wSmJcEFqG), but that's a static conversion so we will never see it inside ObjectsAreEqualValues.

Comment (arjunmahishi) [reply assert/assertions.go]: > But you can convert a complex128 to a complex64

Oh! thats right 🤦🏽‍♂️

**Review by brackendawson — APPROVED** [review]
