### PR TITLE
assert: better formatting for Len() error

### LINKED ISSUE #1482: Error message on Len() assumes string
This error message in `assert.Len` assumes that whatever you are asserting a length about can be formatted with the `%s` format string. 

```go
	if l != length {
		return Fail(t, fmt.Sprintf("\"%s\" should have %d item(s), but has %d", object, length, l), msgAndArgs...)
	}
```

If you look at the failure in e.g. https://drone.grafana.net/grafana/dskit/3189/1/4, I believe this is a []uint32, which is being formatted as `"[%!s(uint32=2452015680) %!s(uint32=2476020736)]"`. 

I think the `%v` format string might be a better fit.

### PR DESCRIPTION
**Pull request by kevinburkesegment**
Previously, the use of %s with array objects meant you would get an error like this:

    "[%!s(int=1) %!s(int=2) %!s(int=3)]\" should have 4 item(s), but has 3

Use %v instead, which provides a much nicer error.

    "[1 2 3]" should have 4 item(s), but has 3

Fixes #1482.

### CODE REVIEW

**Review by dolmen — CHANGES_REQUESTED** [review]
The test suite must cover many more types. I think this will show that `%#v` is more appropriate.

We should also handle the case where the len is large (ex: 1000 items). Displaying the full value is just pollution in that case. That could be handled in a separate MR, but at least the test suite must be structured to allow this future change.

**Comment by kevinburkesegment** [comment]
> We should also handle the case where the len is large (ex: 1000 items). Displaying the full value is just pollution in that case.

To be clear I think the current "%s" formatting also does not do a great job in this case

**Comment by kevinburkesegment** [comment]
I added the types from the other len() tests, except for the channel types, which show up as a pointer address, that will change every single time.

**Review by dolmen — CHANGES_REQUESTED** [review]
We don't need 2 loops on the same test cases.
Let's merge the old tests on the `cases` into your loop.

**Comment by kevinburkesegment** [comment]
> Let's merge the old tests on the cases into your loop.

How do you want me to handle the channel tests?

**Comment by dolmen** [comment]
@kevinburkesegment Skip the format test if the `want` string is `""`.

**Comment by dolmen** [comment]
I just noticed we also have #1405 which is an alternative.

**Comment by kevinburkesegment** [comment]
I'll update the patch today

**Comment by kevinburkesegment** [comment]
OK, updated. I also shortened the test cases

**Comment by kevinburkesegment** [comment]
Hi, just following up - let me know if you'd like further changes here.

File: assert/assertions_test.go [hunk 1]
```diff
@@ -1644,49 +1644,34 @@ func TestLen(t *testing.T) {
...
-
-	for _, c := range cases {
-		False(t, Len(mockT, c.v, c.l), "%#v have %d items", c.v, c.l)
+		False(t, Len(mockT, c.v, c.l+1), "%#v have %d items", c.v, c.l)
+		if c.format != "" {
+			msgMock := new(mockTestingT)
+			Len(msgMock, c.v, 1234567)
+			want := fmt.Sprintf(`"%s" should have 1234567 item(s), but has %d`, c.format, c.l)
+			Contains(t, msgMock.errorString(), want)
+		}
```
Comment (dolmen) [inline assert/assertions_test.go:1674]: I prefer to have the whole expected string in a `want` string and avoid a `want` string built with sprintf. Test code must be boring.

**Review by dolmen — CHANGES_REQUESTED** [review]
Good improvements. We're nearly done.

File: assert/assertions_test.go (hunk 1 above)
Comment (kevinburkesegment) [reply assert/assertions_test.go:1673]: Done

File: assert/assertions_test.go [hunk 2]
```diff
@@ -1644,49 +1644,33 @@ func TestLen(t *testing.T) {
 	ch <- 3
 
 	cases := []struct {
-		v interface{}
-		l int
+		v      interface{}
+		l      int
+		format string
```
Comment (dolmen) [inline assert/assertions_test.go:1649]: Rename to `expected1234567` (because this isn't a format but the expected message) and add a comment `// message when expecting 1234567 items`.

**Review by dolmen — CHANGES_REQUESTED** [review]

File: assert/assertions_test.go (hunk 2 above)
Comment (kevinburkesegment) [reply assert/assertions_test.go]: Done

**Comment by k1ng440** [comment]
LGTM.

**Comment by dolmen** [comment]
@k1ng440 Use the "Review changes" button to post a review, not a comment. 
image

**Review by wwade — APPROVED** [review]
LGTM

**Review by k1ng440 — APPROVED** [review]

**Review by dolmen — APPROVED** [review]
LGTM.

@kevinburkesegment I'm sorry for the time it took and the multiple exchanges, but we achieved together a short patch with a comprehensive test suite. Thank you!

**Comment by kevinburkesegment** [comment]
No worries! Anything I need to do to get this ready for merge?

**Comment by kevinburkesegment** [comment]
Hi, anything I can help with here?

**Comment by kevinburkesegment** [comment]
Hey, just wondering if there's anything I can do to get this ready for merge.

**Comment by arjunmahishi** [comment]
Hi @kevinburkesegment! 

There seems to be [a few panics](https://github.com/stretchr/testify/actions/runs/6970446567/job/18968782955?pr=1485) the tests. Can you please take a look at that?

**Comment by kevinburkesegment** [comment]
I just rebased against latest master and the tests are passing. I checked the panics and I don't see how they are related to the change that I made.

**Comment by arjunmahishi** [comment]
Cool thanks!
Let me find a maintainer who has access to merge this.
