### PR TITLE
assert.YAMLEq: Document mutlidoc behavior

### LINKED ISSUE #1281: Asserting nested yaml documents are working as expected
Asserting nested yaml documents will always pass. 

I would expect following test to fail.
`
package main

import (
	"github.com/stretchr/testify/assert"
	"testing"
)

func TestMultipleYAMLDocuments(t *testing.T) {

	expectedYaml := `
Director:
  name: Spielberg
  Movies:
    - Movie:
        title: E.T.
        year: 1975
    - Movie:
        title: Jaws
        year: 1982
---
Director:
  name: Spielberg
  Movies:
    - Movie:
        title: E.T.
        year: 1975
    - Movie:
        title: Jaws
        year: 1982

`
	actualYaml := `
Director:
  name: Spielberg
  Movies:
    - Movie:
        title: E.T.
        year: 1975
    - Movie:
        title: Jaws
        year: 1982
---
Director:
  name: Spielberg
  Movies:
    - Movie:
        title: E.T.
        year: 1975

`
	assert.YAMLEq(t, expectedYaml, actualYaml, "yaml should be the same")
}

`

### PR DESCRIPTION
**Pull request by brackendawson**
## Summary
Document the limitation that YAMLEq only compares the first document.

## Changes
* Add tests to cover more of the current YAMLEq behavior.
* Document that YAMLEq only compares the first document.

## Motivation
It would be preferable to fix YAMLEq to compare all documents because that's what it outwardly claims to do and is what one would expect it to do. #1284 would do that, but #1579 as made this practically impossible. So in testify v1 we must document the behavior as is.

## Related issues
Addresses but does not resolve #1281

### CODE REVIEW

File: assert/assertions.go [hunk 1]
```diff
@@ -1880,7 +1880,7 @@ func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{
 	return Equal(t, expectedJSONAsInterface, actualJSONAsInterface, msgAndArgs...)
 }
 
-// YAMLEq asserts that two YAML strings are equivalent.
+// YAMLEq asserts that the first document in the two YAML strings is equivalent.
```
Comment (ccoVeille) [inline assert/assertions.go]:
```suggestion
// YAMLEq asserts that the first document in the YAML documents is equivalent to the expected one.
```

This would be better.  First and two didn't sound good

Comment (ccoVeille) [inline assert/assertions.go]: I don't think it's enough.

There should be an example close yo what you have in the unit test.

Comment (brackendawson) [reply assert/assertions.go]: Its not accurate because it also only considers the first document in the expected yaml string.

Comment (ccoVeille) [reply assert/assertions.go]: Oh indeed.

Comment (ccoVeille) [reply assert/assertions.go]: Thanks it's way clearer

File: assert/assertions.go [hunk 2]
```diff
@@ -1880,7 +1880,19 @@ func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{
...
```
Comment (ccoVeille) [inline assert/assertions.go]: The current proposal sounds grammatically incorrect to me.

What about this?

```suggestion
// YAMLEq asserts that the first documents in the two YAML strings are equivalent.
```

Or this maybe


```suggestion
// YAMLEq asserts that the first YAML document in each string is equivalent.
```

Or this

```suggestion
// YAMLEq asserts that the first YAML document in one string is equivalent to the first YAML document in the other string.
```

Wording is a pain, grammar is worst.

File: assert/assertions.go [hunk 3]
```diff
@@ -1880,7 +1880,19 @@ func JSONEq(t TestingT, expected string, actual string, msgAndArgs ...interface{
 	return Equal(t, expectedJSONAsInterface, actualJSONAsInterface, msgAndArgs...)
 }
 
-// YAMLEq asserts that two YAML strings are equivalent.
+// YAMLEq asserts that the first documents in the two YAML strings are equivalent.
```
Comment (ccoVeille) [inline assert/assertions.go:1883]: I'm sorry, I thought about it again.

My problem now us the fact "first documents are the same" could imply that it's about checking the first nth documents

What about these?

```suggestion
// YAMLEq asserts that the first YAML document of each string is equivalent.
```

```suggestion
// YAMLEq asserts that the first document of each YAML string is equivalent.
```
I prefer the first one

Comment (brackendawson) [reply assert/assertions.go:1883]: > YAMLEq asserts that the first YAML document of each string is equivalent.

This implies that the strings contain documents other than YAML.

> YAMLEq asserts that the first document of each YAML string is equivalent.

The first document of each YAML string is equivalent to what?

Your suggestion which I accepted is the most correct.
