### PR TITLE
Fix Call.Unset() panic (issue #1236)

### LINKED ISSUE #1236: [ISSUE] mockCall.Unset cause panic
Hi team, I'm using testify to testing my method but encounter this issue (It only occur if using matchedBy arg)
When I using mock following by example but got error when using mockCall.Unset().
playground: https://go.dev/play/p/oQ2sGSRCtbR

### PR DESCRIPTION
**Pull request by lisitsky**
## Summary
`Unset()` doesn't work as expected in documentation. Instead of unsetting call specification it causes panic.

Reason: During call specification filtering `Unset()` changes len of a `ExpectedCalls` slice while using index from original slice. Under some circumstances it tries to reslice elements beyond of the slice boundaries. That causes panic.

## Changes
The proposed solution uses independent write index to count elements kept in result slice.
Tests (the simplest and  a more complicated cases) and comments are included.

## Motivation
Because core functionality required by users to write tests doesn't work as expected.

```golang
// Unset removes a mock handler from being called.
test.On("func", mock.Anything).Return(nil)  // OK
test.On("func", mock.Anything).Unset()      // panic
```

## Related issues
Closes #1236

### CODE REVIEW

**Comment by lisitsky** [comment]
Hello,  @glesica ,  @boyan-soubachov , @mvdkleijn !
Could you please check this MR - it closes panic and makes tests behavior as it is documented.
Thank you very much!

**Comment by mweibel** [comment]
ping - that'd be great to have fixed :+1:

File: mock/mock.go [hunk 1]
```diff
@@ -218,16 +218,22 @@ func (c *Call) Unset() *Call {
...
-	for i, call := range c.Parent.ExpectedCalls {
+	// in-place filter slice for calls to be removed - iterate from 0'th to last skipping unnecessary ones
+	var index int // write index
+	for _, call := range c.Parent.ExpectedCalls {
 		if call.Method == c.Method {
 			_, diffCount := call.Arguments.Diff(c.Arguments)
 			if diffCount == 0 {
 				foundMatchingCall = true
-				// Remove from ExpectedCalls
-				c.Parent.ExpectedCalls = append(c.Parent.ExpectedCalls[:i], c.Parent.ExpectedCalls[i+1:]...)
```
Comment (felixliou) [inline mock/mock.go:227]: looks good to me

File: mock/mock.go [hunk 2]
```diff
@@ -218,16 +218,22 @@ func (c *Call) Unset() *Call {
 
 	foundMatchingCall := false
 
-	for i, call := range c.Parent.ExpectedCalls {
+	// in-place filter slice for calls to be removed - iterate from 0'th to last skipping unnecessary ones
+	var index int // write index
+	for _, call := range c.Parent.ExpectedCalls {
```
Comment (felixliou) [inline mock/mock.go:223]: modify looks good to me

Comment (lisitsky) [reply mock/mock.go:223]: thank you

**Comment by lisitsky** [comment]
> ping - that'd be great to have fixed 👍

@mweibel, yes, but how to promote it to accept? )

File: mock/mock.go (hunk 2 above)
Comment (lisitsky) [reply mock/mock.go:223]: Hello, @felixliou!
Perhaps I misunderstood you. 
Do you mean "looks ok now, and ready for merge" or you ask me modify the code?
If so, could you pls clarify which modifications are required? Thank you.

Comment (felixliou) [reply mock/mock.go:223]: looks ok now, and ready for merge，but I have not authorized to merge this PR.

Comment (lisitsky) [reply mock/mock.go:223]: Thank you for your feedback. Do you know anybody (possibly maintainers?) who can do it? Could you ping they please?

Comment (felixliou) [reply mock/mock.go:223]: Hi，
@ernesto-jimenez 
@matryer 
@boyan-soubachov 

Please check this pull request.

Thank you very much

**Review by boyan-soubachov — APPROVED** [review]
Thank you for this contribution, approved and merging :)

**Comment by lefinal** [comment]
When can we expect this to be released?
