### PR TITLE
Fixed didPanic to now detect panic(nil).

### LINKED ISSUE #794: didPanic does not detect panic(nil)
This is because you use `recover() != nil` to detect whether a panic  occurred.
I have opened PR  #793 to fix this.

### PR DESCRIPTION
**Pull request by RmbRT**
Previously, the function would not detect panic(nil) calls.
In didPanic, removed the anonymous function call, instead,
added named return values. Added extra test cases for the
panic(nil) call.

Closes #794.

### CODE REVIEW

**Comment by MariusVanDerWijden** [comment]
Nice!

**Review by MariusVanDerWijden — DISMISSED** [review]

**Comment by sebastianst** [comment]
ACK good catch

**Review by sebastianst — DISMISSED** [review]

**Comment by ggwpez** [comment]
Hes my brother :100:

File: assert/assertions.go [hunk 1]
```diff
@@ -901,25 +901,15 @@ func Condition(t TestingT, comp Comparison, msgAndArgs ...interface{}) bool {
...
-
-	}()
-
-	return didPanic, message
+	defer func() { message = recover() }()
+	// call the target function
+	f()
+	didPanic = false
 
+	return
```
Comment (boyan-soubachov) [inline assert/assertions.go:912]: Is this line not redundant/pointless now?

File: assert/assertions_test.go [hunk 2]
```diff
@@ -730,10 +730,18 @@ func TestCondition(t *testing.T) {
 
 func TestDidPanic(t *testing.T) {
 
-	if funcDidPanic, _ := didPanic(func() {
-		panic("Panic!")
-	}); !funcDidPanic {
-		t.Error("didPanic should return true")
+	const panicMsg = "Panic!"
+
+	if funcDidPanic, msg := didPanic(func() {
```
Comment (boyan-soubachov) [inline assert/assertions_test.go:735]: Would it be a bit clearer if we separated these `if` statements into two lines, assignment and `if` check?

e.g.
```
funcDidPanic, msg := didPanic(func() {...})
if !funcDidPanic || msg != panicMsg {
    ...
}
```

**Comment by Antonboom** [comment]
Any updates? :)

**Comment by Antonboom** [comment]
Any updates? :)

**Review by boyan-soubachov — DISMISSED** [review]
Thanks for your contribution :)

**Comment by boyan-soubachov** [comment]
This PR needs to be updated and conflicts resolved before I can merge it.

**Comment by RmbRT** [comment]
Rebased, resolved conflicts.

File: assert/assertions.go (hunk 1 above)
Comment (RmbRT) [reply assert/assertions.go:1021]: I think it's required when returning named return values.

File: assert/assertions_test.go (hunk 2 above)
Comment (RmbRT) [reply assert/assertions_test.go]: I think it's fine as it is. Reads as naturally as any other go code to me.
